### PR TITLE
Lower ubuffer

### PR DESCRIPTION
**Pull request by joyliu37**

### CODE REVIEW

**Comment by joyliu37** [comment]
@dillonhuff I am trying to merge master and I found you also call `garnet_map_module` when generate CoreIR for M1 and M3. 
It seems that you create memory tile for memory component to get the access count. I do not think you map to garnet finally, what's the reason you call that function?

**Comment by dillonhuff** [comment]
@joyliu37 just comment out the garnet mapping for M1 / M3 if it is having problems.

The first two harris variants don't pass in the platonic tests because of an error in the compute units.

**Comment by joyliu37** [comment]
Thanks for the reply. I got all apps passed except upsample and unsharp for M1 and M3. Would you mind to take a look at upsample. I think it's just a small error but I am not sure where to start with debugging.

**Comment by dillonhuff** [comment]
@joyliu37 sure, when did upsample and unsharp start to break? Its very hard to debug these kinds of RTL generation problems, so it would be good to know when the last working state of the code was.

**Comment by joyliu37** [comment]
Opps, it's my bad. I think I forgot to check the cgra_flow test during the deadline. The last time it pass must be the last PR. 
I am checking out to the "merging master commit" and see if there is more recent commit that did not break the test.

**Comment by dillonhuff** [comment]
@joyliu37 in that case could you please `git bisect` the code to find the first place where `cgra_flow` passes? 

https://git-scm.com/docs/git-bisect

**Comment by joyliu37** [comment]
Interesting, after running `git bisect` it points to a commit made by Jeff. 

9f319f512707cdcaf3cdac9730a9016f7bbbf5de is the first bad commit
commit 9f319f512707cdcaf3cdac9730a9016f7bbbf5de
Author: Jeff Setter <setter@stanford.edu>
Date:   Sun Nov 22 11:02:32 2020 -0800

    Fix unsharp kernel values

:040000 040000 1f6319ddcb298768af6c0a9bcde2173bf0c0256e 70bf846aedcf09ef8b74730d5f6aa05d47e2cf24 M      coreir_compute
:100644 100644 e7a3b5b5965e75563cab5fe35b7baab2a728f415 95b8dad272c8b0846095b1655229845ccd5f6695 M      example_progs.cpp
:100644 100644 cd0297dd23056361b547b48541a4db0a88e1e0e0 69158a46e7bda6e6da7f6039e58a5d489a71ed00 M      unsharp_compute.h

**Comment by joyliu37** [comment]
@dillonhuff I am also tracing back what caused the up_sample error. I modify the up_sample app in `example_prog.cpp` in this commit https://github.com/dillonhuff/clockwork/pull/132/commits/7ec111049ef36b5b60f92bad5fe2e7cfa939e41a .
When I change back to original format, it pass the test. Could you check what happens in your backend, when I made this change in the storage order?

**Comment by dillonhuff** [comment]
@joyliu37 when I check out `example_progs.cpp` from that commit I get the following error:

```bash
Error in cgra_up_sample_cpu_vs_verilog_comparison: After optimization, at output 2 unoptimized_res != optimized_res
	unoptimized = 0000000011000110
	optimized   = 0000000000000000
clockwork: utils.cpp:89: void compare(const string&, std::vector<std::__cxx11::basic_string<char> >&, std::vector<std::__cxx11::basic_string<char> >&): Assertion `unoptimized_res.at(i) == optimized_res.at(i)' failed.
./rebuild_and_run.sh: line 8:  2502 Aborted                 (core dumped) ./clockwork $1
```

`up_sample` works if I do not check out that commit.

**Comment by joyliu37** [comment]
@dillonhuff You are correct, the only difference I make is that I change the storage order in the upsample apps. Could you support the storage order in that commit.

**Comment by joyliu37** [comment]
I assume that the right most dimension is the inner most dimension and will be stored in the nearby memory word. 
https://github.com/dillonhuff/clockwork/blob/7ec111049ef36b5b60f92bad5fe2e7cfa939e41a/example_progs.cpp#L2531

**Comment by joyliu37** [comment]
> Interesting, after running `git bisect` it points to a commit made by Jeff.
> 
> [9f319f5](https://github.com/dillonhuff/clockwork/commit/9f319f512707cdcaf3cdac9730a9016f7bbbf5de) is the first bad commit
> commit [9f319f5](https://github.com/dillonhuff/clockwork/commit/9f319f512707cdcaf3cdac9730a9016f7bbbf5de)
> Author: Jeff Setter [setter@stanford.edu](mailto:setter@stanford.edu)
> Date: Sun Nov 22 11:02:32 2020 -0800
> 
> ```
> Fix unsharp kernel values
> ```
> 
> :040000 040000 1f6319ddcb298768af6c0a9bcde2173bf0c0256e 70bf846aedcf09ef8b74730d5f6aa05d47e2cf24 M coreir_compute
> :100644 100644 e7a3b5b5965e75563cab5fe35b7baab2a728f415 95b8dad272c8b0846095b1655229845ccd5f6695 M example_progs.cpp
> :100644 100644 cd0297dd23056361b547b48541a4db0a88e1e0e0 69158a46e7bda6e6da7f6039e58a5d489a71ed00 M unsharp_compute.h

It seems that unsharp in the most update-to-date master branch is falling as well. The bug is related to this commit.

**Comment by dillonhuff** [comment]
@joyliu37 yes I see the unsharp failure as well. We should just revert the version of the app to before Jeff's commit.

The order of variables in the array accesses in the input `prog` does not mean anything for the physical layout of the final re-use buffer for that array, so I don't understand what you mean when you say "Could you support the storage order in that commit."

**Comment by joyliu37** [comment]
> @joyliu37 yes I see the unsharp failure as well. We should just revert the version of the app to before Jeff's commit.
> 
I think Jeff found a bug in the unsharp app so that he made that PR. @jeffsetter Jeff could you confirm the reason why you update the unsharp app?

> The order of variables in the array accesses in the input `prog` does not mean anything for the physical layout of the final re-use buffer for that array, so I don't understand what you mean when you say "Could you support the storage order in that commit."
@dillonhuff  I think in some point we need to linearize the high dimensional address domain into 1D. In the single port memory tile backend, I put the right most dimension in the inner-most by default. I think you also make that assumption right? Or you have another way to flatten the address into 1D?

**Comment by dillonhuff** [comment]
@joyliu37 I honestly don't remember which way I lay things out by default. Why do you think that is causing the bug? As long as the order is consistent it shouldn't matter right?

**Comment by joyliu37** [comment]
>As long as the order is consistent it shouldn't matter right?

This is the point, the original up_sample app order is not consistent with the other apps. My commit make it the same as others. Could you double check it? Do you have time to talk about this issue on zoom tomorrow? Like 10am?

**Comment by jeffsetter** [comment]
I recall updating unsharp so that the output image actually looks good.

**Comment by joyliu37** [comment]
> I recall updating unsharp so that the output image actually looks good.

Is the output image in garnet test?

**Pull request merged**
