### PR TITLE
Auto vec

### PR DESCRIPTION
**Pull request by joyliu37**
Merge into master.

### CODE REVIEW

**Comment by dillonhuff** [comment]
@joyliu37 looks good overall. Could you please git rm -f the following files:

```
	C_opt.cpp
	gray_naive.cpp
	gray_naive.h
	gray_opt.cpp
	gray_opt.h
	gray_opt_compute_units.h
	jacobi2d.cpp
	pointwise.cpp
	soda_blur.cpp
	stencil_3d.cpp
	t0_naive.cpp
	t0_naive.h
	t0_opt.cpp
	t0_opt.h
```

**Comment by joyliu37** [comment]
Sure. But it should not be merged now. 
There are still some conflict, I could not run the test. I am fixing it now.

**Comment by dillonhuff** [comment]
Yes I see that some functions are duplicated in isl_utils, that needs to be fixed. How soon will that be done?

**Comment by joyliu37** [comment]
OK. I think it is done. And I am waiting for the test to finish.

**Pull request merged**
