### PR TITLE
Halide apps

### PR DESCRIPTION
**Pull request by jeffsetter**
Updates to unsharp compute, rom test, and harris

### CODE REVIEW

**Comment by dillonhuff** [comment]
@jeffsetter thanks!

Two things: harris now needs a compute unit called `hcompute_padded16_stencil`, but I don't see it in `harris.cpp`

There is a version control marker in `rom_compute.h`

**Comment by jeffsetter** [comment]
Which file is `harris.cpp`? Are you referring to `./harris_memory.cpp`?

Fixed `rom_compute.h`

**Comment by dillonhuff** [comment]
@jeffsetter sorry, I meant to say the harris generator function in `example_progs.cpp`

**Comment by jeffsetter** [comment]
Do you want me to modify `harris` or `halide_harris`?

**Comment by dillonhuff** [comment]
`harris` please

**Comment by jeffsetter** [comment]
Could you try `harris` again? I updated all of the files again and they seem to be up-to-date for me.

**Comment by dillonhuff** [comment]
@jeffsetter retried and everything looks good. Thanks!

**Pull request closed without merging**
