### PR TITLE
Lower ubuffer

### PR DESCRIPTION
**Pull request by joyliu37**
Let's merge the lower buffer branch directly, I run all the test directly. 

Adding a coreirlib make target.
Rearrange the include sequence.
Fix a bug in bank merging.

### CODE REVIEW

**Comment by joyliu37** [comment]
Sorry for the missing file, there are tons of generated hls code in the untracked file.

**Comment by dillonhuff** [comment]
@joyliu37 when I checkout your branch and run it I get a dynamic linking error:

```bash
dyld: lazy symbol binding failed: Symbol not found: _isl_union_map_card
  Referenced from: lib/libclkwrk.dylib
  Expected in: flat namespace

dyld: Symbol not found: _isl_union_map_card
  Referenced from: lib/libclkwrk.dylib
  Expected in: flat namespace

./rebuild_and_run.sh: line 8: 37875 Abort trap: 6           ./clockwork $1
```

**Comment by joyliu37** [comment]
hmm, let me try to rebuild it on my mac.

**Comment by joyliu37** [comment]
That is wield, I could run the test script without problem on my mac. Did you do a make clean?

**Comment by dillonhuff** [comment]
@joyliu37 your new makefile is deleting the barvinok dylibs when you make clean. You cannot just remove all of lib because that is where the install dep script puts barvinok / polylib

**Comment by joyliu37** [comment]
oops. I install it in a different directory.  Since I create another coreIR library in that folder.

**Comment by dillonhuff** [comment]
@joyliu37 I see. Please just add specific files to that rm that you want to delete and then I will re-run the code.

**Comment by dillonhuff** [comment]
@joyliu37 I rebuilt and the tests are now running. I'll merge this when they finish (assuming all tests pass). Please don't push anything new to this branch.

**Comment by dillonhuff** [comment]
@joyliu37 `void sum_diffs_test()` fails now. Do all of the tests pass on your machine?

The error is:

```bash
Assertion failed: (bnk.read_delays.size() == 2), function generate_bank_and_merge, file ubuffer.cpp, line 1453.
./rebuild_and_run.sh: line 8: 61897 Abort trap: 6           ./clockwork $1
```

**Comment by joyliu37** [comment]
Yeah. It passed on my machine. I rerun this specific test and did not see this error. 
But I do modify the generate_bank_and_merge in these PR.

**Comment by dillonhuff** [comment]
@joyliu37 hmmm, thats odd.

Would you mind running that test and sending me the log?

**Comment by joyliu37** [comment]
Do you want the full set of test? or just the `sum_diffs_test`.

**Comment by joyliu37** [comment]
I got this in the log. Did it mean that I did not run the test_bench, but just generate the file?
mv: rename sum_diffs_kernel.h to ./soda_codes/sum_diffs/soda_code/sum_diffs_kernel.h: No such file or directory
mv: rename regression_tb_sum_diffs.cpp to ./soda_codes/sum_diffs/our_code/regression_tb_sum_diffs.cpp: No such file or directory
chmod: run_tb_sum_diffs.sh: No such file or directory
mv: rename run_tb_sum_diffs.sh to ./soda_codes/sum_diffs/our_code/run_tb_sum_diffs.sh: No such file or directory
chmod: aws_run_tb_sum_diffs.sh: No such file or directory
mv: rename aws_run_tb_sum_diffs.sh to ./soda_codes/sum_diffs/our_code/aws_run_tb_sum_diffs.sh: No such file or directory
mv: rename sum_diffs.soda to ./soda_codes/sum_diffs/soda_code/sum_diffs.soda: No such file or directory

**Comment by dillonhuff** [comment]
@joyliu37 never mind about running the test. There is a sporadic failure on my end. I will look into it more.

**Pull request merged**
