### PR TITLE
Coreir

### PR DESCRIPTION
**Pull request by joyliu37**

### CODE REVIEW

**Comment by dillonhuff** [comment]
@joyliu37 thanks for pushing an update. Why can't the code run and is there any way I can help?

**Comment by joyliu37** [comment]
I think it's good to merge now. Could you double check the Makefile, see if there are some mistakes.

**Comment by dillonhuff** [comment]
@joyliu37 thanks for fixing that. However I checked travis and actually that build is failing because of one of the new arguments in the makefile:
https://travis-ci.org/github/dillonhuff/clockwork/builds/693744921

**Comment by dillonhuff** [comment]
@joyliu37 thanks for changing that. It seems that gcc also does not like the use of `set` without `std` because of a template called `set` in NTL. As a result travis is still failing to build. Could you change `set` to `std::set` in the code?

**Pull request merged**
