### PR TITLE
Lower ubuffer

### PR DESCRIPTION
**Pull request by joyliu37**
Merge ubuffer coreir codegen

### CODE REVIEW

**Comment by dillonhuff** [comment]
@joyliu37 did you add coreir_lib.h and coreir_lib.cpp to the repo?

**Comment by joyliu37** [comment]
Add them.

**Comment by dillonhuff** [comment]
@joyliu37 the code does not build on my machine. I get the following errors:

```bash
./rebuild_and_run.sh 
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c -o qexpr.o qexpr.cpp
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c -o app.o app.cpp
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c -o isl_utils.o isl_utils.cpp
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c -o prog.o prog.cpp
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c -o codegen.o codegen.cpp
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c -o minihls.o minihls.cpp
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c -o ubuffer.o ubuffer.cpp
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c -o coreir_backend.o coreir_backend.cpp
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c -o coreir_lib.o coreir_lib.cpp
/Users/dillon/Downloads/clang+llvm-9.0.0-x86_64-darwin-apple/bin/clang++ -std=c++17 -I /Users/dillon/CppWorkspace/ubuffer-example/barvinok-0.41/isl -I /Users/dillon/CppWorkspace/ubuffer-example/include -c build_set_test.cpp -o clockwork.o
In file included from ubuffer.cpp:1:
./ubuffer.h:625:5: error: unknown type name 'json'
    json config_file;
    ^
./ubuffer.h:634:21: error: unknown type name 'json'
    void set_config(json config) {
                    ^
In file included from build_set_test.cpp:2:
./ubuffer.h:625:5: error: unknown type name 'json'
    json config_file;
    ^
In file included from prog.cpp:1:
In file included from ./prog.h:7:
./ubuffer.h:625:5: error: unknown type name 'json'
    json config_file;
    ^
./ubuffer.h:634:21: error: unknown type name 'json'
    void set_config(json config) {
                    ^
./ubuffer.h:634:21: error: unknown type name 'json'
    void set_config(json config) {
                    ^
In file included from codegen.cpp:1:
In file included from ./codegen.h:4:
./ubuffer.h:625:5: error: unknown type name 'json'
    json config_file;
    ^
./ubuffer.h:634:21: error: unknown type name 'json'
    void set_config(json config) {
                    ^
build_set_test.cpp:788:24: error: no viable overloaded '='
    buffers[sram.name] = sram;
    ~~~~~~~~~~~~~~~~~~ ^ ~~~~
./ubuffer.h:601:7: note: candidate function (the implicit move assignment operator) not viable: no known
      conversion from 'UBuffer' to 'UBuffer &&' for 1st argument
class UBuffer {
      ^
build_set_test.cpp:789:22: error: no viable overloaded '='
    buffers[tb.name] = tb;
    ~~~~~~~~~~~~~~~~ ^ ~~
./ubuffer.h:601:7: note: candidate function (the implicit move assignment operator) not viable: no known
      conversion from 'UBuffer' to 'UBuffer &&' for 1st argument
class UBuffer {
      ^
^Cmake: *** [clockwork.o] Interrupt: 2
make: *** [ubuffer.o] Interrupt: 2
make: *** [minihls.o] Interrupt: 2
make: *** [codegen.o] Interrupt: 2
make: *** [prog.o] Interrupt: 2
make: *** [isl_utils.o] Interrupt: 2
make: *** [app.o] Interrupt: 2
```

**Comment by joyliu37** [comment]
Oops, I forget to add the header guard. check this out

**Comment by dillonhuff** [comment]
@joyliu37 now I get a unit test failure with `COREIR=0`:

```bash
Assertion failed: (test_str == gold_str), function compare_to_gold, file ./utils.h, line 390.
./rebuild_and_run.sh: line 8: 66652 Abort trap: 6           ./clockwork $1
```

**Comment by joyliu37** [comment]
Is it working now?

**Comment by dillonhuff** [comment]
@joyliu37 yes the tests just finished.

**Pull request merged**
