### PR TITLE
Fix unsharp with channel in innermost loop

### PR DESCRIPTION
**Pull request by jeffsetter**
- fixed unsharp (and slight app modifications)

### CODE REVIEW

**Comment by dillonhuff** [comment]
@jeffsetter I pulled this version. Could you unroll the color channels in the inner loops as well?

**Comment by jeffsetter** [comment]
Do you mean unroll the input and output so it reads/writes 3 channels a cycle?

**Comment by dillonhuff** [comment]
@jeffsetter yes

**Comment by dillonhuff** [comment]
@jeffsetter thanks!

Now it seems there is a width issue in the compute units:

```bash
ERROR: cu_op_hcompute_ratio_stencil: Cannot wire together
  inner_compute.out_ratio_stencil : Bit[16]
  self.ratio_stencil_op_hcompute_ratio_stencil_write[0] : BitIn[8]
```

**Pull request merged**
