### PR TITLE
Added reinterpret to standard compute

### PR DESCRIPTION
**Pull request by jeffsetter**
added
 - reinterpret (which copies bits)
 - float_from_bits (using a reinterpret from a uint32 number to float)

### CODE REVIEW

**Comment by dillonhuff** [comment]
@jeffsetter did the apps work with these additions?

**Comment by jeffsetter** [comment]
yes, they worked with this

**Comment by dillonhuff** [comment]
@jeffsetter excellent!

**Comment by dillonhuff** [comment]
@jeffsetter I'm running a long test locally, but I'll merge soon.

**Pull request merged**
